apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ticketing.dev
      http:
        paths: # Attempts to match the paths in the path order
          - path: /api/users/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 3000
          - path: /?(.*) # Catch all paths, therefore at the bottom
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-service
                port:
                  number: 3000
